package com.github.magic.cache;

import java.io.Serializable;
import java.nio.file.Path;
import java.util.Date;

/**
 * <p>The record to store as a cache entry, the caching system works for the following type of response: </p>
 * <ul>
 *     <li>Static content: Etag will be generated through this <a href="https://stackoverflow.com/questions/4533/http-generating-etag-header">method</a> from stackoverflow, and keep a file reference to that file</li>
 *     <li>Dynamic content: This includes response from database or hardcoded value (json, string,...), an Etag will be generated by calling {@link ETagGenerator#generateEtagForDynamicResponse(byte[])} (MD5 hashing), with no file associated with it</li>
 * </ul>
 */
public record CacheEntry(int max_age, Date createdSince, Path file, String encoding, String language, byte[] content) {
    @Override
    public String toString() {
        return "Expires: " + isStale() ;
    }

    public boolean isStale(){
        return (new Date().getTime() > (createdSince.getTime() + max_age));
    }
}
