name: Create Release

on:
  workflow_dispatch:

jobs:
  # Extract the project.version from the pom.xml file
  extract_version:
    outputs:
      version_label: ${{ steps.extract_version.outputs.version_label }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "{version_label}={$version}" >> $GITHUB_OUTPUT

  release:
    runs-on: ubuntu-latest
    needs: extract-version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.extract_version.outputs.version_label }}
          release_name: ${{ needs.extract_version.outputs.version_label }}
          body: "Automatically generated release for version ${{ needs.extract_version.outputs.version_label }}."
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/magic-ws-${{ needs.extract_version.outputs.version_label }}.jar
          asset_name: magic-ws-${{ needs.extract_version.outputs.version_label }}.jar
          asset_content_type: application/java-archive